architect:
  - l3r8yJ
merge:
  script:
    - ""
release:
  pre: false
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    git commit -am "${tag}"
    # add your release pipeline
